### ISSUE TITLE
SWSalesSetup::is_login_page() should check for PMPro frontend login as well

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/sitewide-sales#27]
Function in code: https://github.com/strangerstudios/sitewide-sales/blob/747163236937b1e592c73319fd3e7fe587594f5a/includes/classes/class-swsales-setup.php#L57-L68

**Comment by andrewlimaza** [comment]
Fixed in Pull Request -> https://github.com/strangerstudios/sitewide-sales/pull/29
