### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function pmpro_recaptcha_get_html

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/sitewide-sales#85]
**Describe the bug**
Fatal error appears on the checkout page.

**To Reproduce**
1. Set up a Sitewide Sale
2. Go to the Sitewide Sale landing page 
3. Enable reCAPTCHA
4. See error: `Fatal error: Uncaught Error: Call to undefined function pmpro_recaptcha_get_html() in /Users/xxyy/Local Sites/test/app/public/wp-content/plugins/paid-memberships-pro/pages/checkout.php on line 501`. This error doesn't show when Sitewide Sales is deactivated.
**Screenshot**
![image](https://user-images.githubusercontent.com/4752949/163603551-cb9aeb97-20f2-464a-b1ae-0e81ade80276.png)

**Expected behavior**
This error should not be shown.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the Sitewide Sales and Paid Memberships Pro  active. When Sitewide Sales is deactivated, this error is gone.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.7.5, Sitewide Sales 1.2, Twenty Twenty-One 1.4, WordPress 5.9.3, and PHP 7.4.1.
```
</details>

**Comment by michaelbeil** [comment]
This happens with PHP 7.3.5 and 8 as well.

```
Call Stack
--

1 | 0.0002 | 411272 | {main}(  ) | .../index.php:0
2 | 0.0003 | 411544 | require( '/Users/xxyy/Local Sites/test/app/public/wp-blog-header.php' ) | .../index.php:17
3 | 0.1843 | 6461072 | require_once( '/Users/xxyy/Local Sites/test/app/public/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19
4 | 0.1902 | 6570376 | include( '/Users/xxyy/Local Sites/test/app/public/wp-content/themes/memberlite/page.php' ) | .../template-loader.php:106
5 | 0.2916 | 7660504 | get_template_part(  ) | .../page.php:20
6 | 0.2916 | 7661080 | locate_template(  ) | .../general-template.php:204
7 | 0.2916 | 7661240 | load_template(  ) | .../template.php:716
8 | 0.2919 | 7661784 | require( '/Users/xxyy/Local Sites/test/app/public/wp-content/themes/memberlite/components/page/content-page.php' ) | .../template.php:772
9 | 0.2924 | 7626296 | the_content(  ) | .../content-page.php:12
10 | 0.2926 | 7626320 | apply_filters(  ) | .../post-template.php:253
11 | 0.2926 | 7626720 | WP_Hook->apply_filters(  ) | .../plugin.php:189
12 | 0.2932 | 7631152 | do_shortcode(  ) | .../class-wp-hook.php:307
13 | 0.2932 | 7633400 | preg_replace_callback (  ) | .../shortcodes.php:228
14 | 0.2932 | 7634024 | do_shortcode_tag(  ) | .../shortcodes.php:228
15 | 0.2933 | 7634024 | pmpro_pages_shortcode(  ) | .../shortcodes.php:356
16 | 0.2933 | 7634024 | pmpro_loadTemplate(  ) | .../init.php:85
17 | 0.2944 | 7655656 | include( '/Users/xxyy/Local Sites/test/app/public/wp-content/plugins/paid-memberships-pro/pages/checkout.php' ) | .../functions.php:384
 
```

**Comment by kimcoleman** [comment]
@dparker1005 lets try to recreate this. We aren't having this issue on our own membership checkout pages with Sitewide Sales.
